CREATE SCHEMA IF NOT EXISTS core;
CREATE SCHEMA IF NOT EXISTS eps;
CREATE SCHEMA IF NOT EXISTS wms;
CREATE SCHEMA IF NOT EXISTS mro;
CREATE SCHEMA IF NOT EXISTS prm;

GRANT ALL ON SCHEMA core TO ems_admin;
GRANT ALL ON SCHEMA eps TO ems_admin;
GRANT ALL ON SCHEMA wms TO ems_admin;
GRANT ALL ON SCHEMA mro TO ems_admin;
GRANT ALL ON SCHEMA prm TO ems_admin;
